# SPDX-FileCopyrightText: 2022 German Aerospace Center (DLR)
# SPDX-FileContributor: Alexander Weinert <alexander.weinert@dlr.de>
#
# SPDX-License-Identifier: MIT

variables:
  DOCKER_AUTH_CONFIG: '{ "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKERAUTH" } }}'

stages:
  - check

reuse-compliance:
  stage: check
  image:
    name: fsfe/reuse:1.0.0
    entrypoint: [""] # workaround, cf. https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692
  tags:
    - docker
  script:
    - reuse lint

cff-compliance:
  stage: check
  image:
    name: citationcff/cffconvert:2.0.0
    entrypoint: [""] # workaround, cf. https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2692
  tags:
    - docker
  script:
    - cffconvert --validate
